name: Docker Image CI

on:
  push:
    branches: [ "lagoonize" ]
    tags:
    - 'lagoonize-*'
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: bgaioyukon
        password: dckr_pat_fletdTlVXd0Ozf3hYmIyqREdY0E

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: bgaioyukon/careerpathsbase
        tags: |
          type=match,pattern=lagoonize-(.*),group=1

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: lagoon/cli.dockerfile
        push: true
        tags: bgaioyukon/careerpathsbase:latest , ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
