name: Docker Image CI

on:
  push:
    branches: [ "lagoonize" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file lagoon/cli.dockerfile --tag careerpathsbase:$(date +%s) --tag careerpathsbase:latest


    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: bgaioyukon
        password: dckr_pat_fletdTlVXd0Ozf3hYmIyqREdY0E

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: bgaioyukon/careerpathsbase:latest, careerpathsbase:$(date +%s) 
